# Generated by Django 3.2.8 on 2022-03-05 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-updated_on']},
        ),
    ]
