# Generated by Django 3.1 on 2021-10-10 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Contestant'), (2, 'Proctor'), (3, 'Question Writer'), (4, 'Organizer')], default=1)),
                ('team_admin', models.BooleanField(default=False)),
                ('fsu_id', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('fsu_num', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(blank=True, to='manager.Course')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_team', to='register.team')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.faculty'),
        ),
    ]
