# Generated by Django 3.2.13 on 2022-05-14 20:28

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fsu_num',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', blank=True, min_length=7, null=True, prefix=''),
        ),
    ]
