# Generated by Django 3.1 on 2020-08-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='sections',
        ),
    ]
