# Generated by Django 3.2.15 on 2022-09-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_profile_fsu_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='announcement_email_opt_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Contestant'), (2, 'Docent'), (3, 'Proctor'), (4, 'Question Writer'), (5, 'Organizer')], default=1),
        ),
    ]
