# Generated by Django 4.2.25 on 2026-02-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20220909_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passed_cop3330',
            field=models.BooleanField(default=True),
        ),
    ]
