# Generated by Django 3.1 on 2020-09-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Contestant'), (2, 'Proctor'), (3, 'Question Writer'), (4, 'Organizer')], default=1),
        ),
    ]
