# Generated by Django 3.1 on 2020-08-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='contest_password',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
