# Generated by Django 3.0.8 on 2020-08-08 05:03

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=django_mysql.models.ListTextField(models.CharField(max_length=181), default=[], max_length=543, size=3),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Lower Division'), (2, 'Upper Division')]),
        ),
    ]
