# Generated by Django 4.1.7 on 2023-04-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
