# Generated by Django 3.0.8 on 2020-08-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200808_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(blank=True, to='register.Course'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fsu_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fsu_num',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Upper Division'), (2, 'Lower Division')]),
        ),
    ]
