# Generated by Django 4.1.7 on 2023-04-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_team_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='faculty',
            field=models.BooleanField(default=False),
        ),
    ]
