# Generated by Django 3.1 on 2020-10-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_team_questions_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='num_members',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
