# Generated by Django 4.2.4 on 2025-02-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_team_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='last_submission',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
