# Generated by Django 4.2.25 on 2026-03-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_team_last_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='questions_for_extra_credit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
