# Generated by Django 3.1 on 2021-02-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.FileField(blank=True, upload_to='uploads/')),
                ('ec_processed', models.BooleanField(default=False)),
            ],
        ),
    ]
