# Generated by Django 3.1 on 2021-09-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_date', models.DateField()),
                ('contest_doors', models.TimeField()),
                ('contest_start', models.TimeField()),
                ('contest_freeze', models.TimeField()),
                ('contest_end', models.TimeField()),
                ('contest_awards', models.TimeField()),
                ('results', models.FileField(blank=True, upload_to='uploads/')),
                ('ec_processed', models.BooleanField(default=False)),
            ],
        ),
    ]
