# Generated by Django 3.2.12 on 2022-03-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='team_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='volunteer_pin',
            field=models.CharField(default='thankyou', max_length=8),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_awards',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_doors',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_freeze',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
