# Generated by Django 3.2.15 on 2022-09-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestadmin', '0003_auto_20220321_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='lunch_form_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
