# Generated by Django 3.2.15 on 2022-09-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestadmin', '0004_contest_lunch_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='lfg_active',
            field=models.BooleanField(default=False),
        ),
    ]
