# Generated by Django 4.1.6 on 2023-02-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestadmin', '0005_contest_lfg_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='order_tshirt_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
